### ISSUE TITLE
package org.mineacademy.fo.command.annotation does not exist

### ISSUE THREAD

**Issue by Timtendo12** [kangarko/PluginTemplate#3]
This template uses a foundation 6 feature which has not released yet, This keeps us from building the project. Could you fix this?

**Comment by kangarko** [comment]
Thanks, fixed. Just to clarify the confusion, It's not possible to use anything from Foundation 6 because pom.xml uses Foundation 5. However between 5.11 and 5.12 the annotation package got moved and I forgot to make appropriate changes, which is now fixed in the latest commit and described at https://www.skool.com/project-orion/ackage-orgmineacademyfocommandannotation-does-not-exist

Thank you!
